services:
  postgres:
    image: "postgres:16"
    environment:
      POSTGRES_DB: "overtake"
      POSTGRES_USER: "overtake"
      POSTGRES_PASSWORD: "dbpasswd"

  server:
    build:
      context: "./server/"
      dockerfile: "./Dockerfile"
    tty: true
    ports:
      - "8080:8080"
    environment:
      DATABASE: "Host=postgres;Username=overtake;Password=dbpasswd;Database=overtake"
