services:
  postgres:
    image: "postgres:16"
    environment:
      POSTGRES_DB: "overtake"
      POSTGRES_USER: "overtake"
      POSTGRES_PASSWORD: "dbpasswd"

  server:
    build:
      context: "./server/"
      dockerfile: "./Dockerfile"
    tty: true
    ports:
      - "8080:8080"
    environment:
      DATABASE: "Host=postgres;Username=overtake;Password=dbpasswd;Database=overtake"

  web:
    build:
      context: "./web/"
      dockerfile: "./Dockerfile"
    volumes:
      - ./web/:/app/ #mount local 'web' directory into the container
    ports:
      - "3000:3000"
    command: npm run dev #enable live updating after running 'docker compose up -d --build'
    environment:
        CHOKIDAR_USEPOLLING: "true" #helps ensure live reload works on all systems